### ISSUE TITLE
Bottom part of the selectable-dates-view clipped

### ISSUE THREAD

**Issue by TimvanSteenbergen** [hunterkoppenclevr/Clevr-DatePicker#1]
Can you make the position of the month dropdown similar to that of the calendar itself?
![afbeelding](https://user-images.githubusercontent.com/3594338/183507655-f6fe1483-c0e9-4a4b-a766-e1c3a44a026e.png)

**Comment by hunterkoppenclevr** [comment]
This one should also be solved now 👍
