### ISSUE TITLE
Option to add a label

### ISSUE THREAD

**Issue by TimvanSteenbergen** [hunterkoppenclevr/Clevr-DatePicker#2]
Can you add an option to make this inputbox also have a label. This will make it way easier to seemlessly integrate the datepicker in a form.
![afbeelding](https://user-images.githubusercontent.com/3594338/183508066-4e119c0d-8685-4f0a-a205-6c84874c4dc2.png)

**Comment by hunterkoppenclevr** [comment]
I added the label as an option
