### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by LisettedenBraber** [hunterkoppenclevr/Clevr-DatePicker#4]
I have an issue with the event handlers in the datepicker. When I change the date, the eventhandlers don't response on the date picked. They respond with the previous date that was selected. I have a workaround for myself that solved the issue, I added a 'Wait' activity in my nanoflow. But this is not the best solution I think.

**Comment by hunterkoppenclevr** [comment]
Thank you very much for reporting this issue! It should now be solved with the latest update 👍, if you still experience the same problem after updating please re-open the issue.
